'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VB_Final_Exam_Project.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AIVB() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AIVB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AIVB2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AIVB2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_ball_image_0013() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-ball-image-0013", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_computer_image_0085() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-computer-image-0085", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_devil_image_0172() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-devil-image-0172", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_diamond_and_gem_image_0002() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-diamond-and-gem-image-0002", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_diamond_and_gem_image_0008() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-diamond-and-gem-image-0008", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_diamond_and_gem_image_0010() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-diamond-and-gem-image-0010", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_dice_image_0016() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-dice-image-0016", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_effect_image_0005() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-effect-image-0005", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_effect_image_0009() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-effect-image-0009", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_effect_image_0010() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-effect-image-0010", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_effect_image_0062() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-effect-image-0062", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_effect_image_0063() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-effect-image-0063", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_effect_image_0064() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-effect-image-0064", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_effect_image_0065() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-effect-image-0065", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_effect_image_0081() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-effect-image-0081", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_effect_image_0172() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-effect-image-0172", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_effect_image_0203() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-effect-image-0203", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_fire_image_0099() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-fire-image-0099", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_fire_image_0371() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-fire-image-0371", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_heart_image_0503() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-heart-image-0503", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_money_image_0011() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-money-image-0011", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_money_image_0049() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-money-image-0049", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_money_image_0055() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-money-image-0055", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_money_image_0062() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-money-image-0062", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0007() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0007", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0020() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0020", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0038() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0038", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0041() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0041", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0043() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0043", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0045() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0045", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_00451() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-00451", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_00452() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-00452", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0046() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0046", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0053() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0053", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_00531() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-00531", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0065() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0065", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0068() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0068", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_00681() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-00681", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_00682() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-00682", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0083() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0083", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0104() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0104", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0108() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0108", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0109() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0109", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0110() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0110", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_01232() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-01232", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0158() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0158", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_monster_image_0190() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-monster-image-0190", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_witch_image_0128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-witch-image-0128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backtiles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backtiles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property BloodBorne() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("BloodBorne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blue_tiles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue tiles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brick_map() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_map", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brickfinal2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brickfinal2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brickfinal3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brickfinal3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CrackLounge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CrackLounge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dice1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dice1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dice11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dice11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dice2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dice2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dice3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dice3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dice4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dice4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dice5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dice5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dice51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dice51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dice6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dice6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DirtTile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DirtTile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property finalgrass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("finalgrass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property first_lanscape_practice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("first lanscape practice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FirstTile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FirstTile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Flyingmonster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flyingmonster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gamble_tile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gamble tile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property green_map() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_map", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenMonster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenMonster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grey_tiles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grey tiles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property house1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("house1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lava_map() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lava_map", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lava3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lava3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lavafinal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lavafinal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lavaLevel3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lavaLevel3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lavaLevel31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lavaLevel31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lavaLevel32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lavaLevel32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lavaLevel3final() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lavaLevel3final", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lightinggif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightinggif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loan_tile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loan tile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property map() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("map", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Monster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Monster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property potion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("potion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property second_lava_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("second lava 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skullgif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skullgif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ThatsLifeVB() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ThatsLifeVB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property TombRaider() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("TombRaider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property top_map() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top map", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TreasureChest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TreasureChest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TreasureChest1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TreasureChest1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TreasureChest2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TreasureChest2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property TwlightZone() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("TwlightZone", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
